### ISSUE TITLE
Can we get an updated catalog.csv?

### ISSUE THREAD

**Issue by xrotwang** [langsci/opendata#6]

**Comment by xrotwang** [comment]
merci!

**Comment by Glottotopia** [comment]
NB: new commit with better object language metadata @xrotwang

**Comment by xrotwang** [comment]
FYI: Here's what `linglit update langsci .` did to the `raw_texfiles` repos after the catalog update
https://github.com/langsci/raw_texfiles/commit/aa6d4d934cb4e4bc133c27e89f0ed2fcb92bd46f
