### ISSUE TITLE
breaking change for OERSI integration: catalogue.csv has a header for 16 columns the following records only have 13

### ISSUE THREAD

**Issue by TobiasNx** [langsci/opendata#8]
With https://github.com/langsci/opendata/commit/df9f57f7ac1d5e15c4118a8928028e20b9046b19 you introduce changes that break our integration process for OERSI.
 
was:
```TSV
ID DOI edited metalanguage objectlanguage license superseded pages series seriesnumber creators title year
```

now is:

```TSV
ID DOI edited metalanguage objectlanguage license superseded pages series seriesnumber book_title year creator institution chapter_author chapter_title
```

there are now 3 additional columns in the header as well as one change in the header names `creators` -> `creators`

The records in the catalogue csv do not have the additional three columns and therefore break our daily integration process into OERSI.
Also the renaming of the column `creators`->`creator` would us loose the `creator` that we could fetch before.

Could you give a little context for the change and add at least placeholders for the `institution`, `chapter_author` and `chapter_title`.
That would be great.

**Comment by Glottotopia** [comment]
sorry for this. I updated the script to optionally include chapter metadata as well for other purposes, not aware that this would break your pipeline. My current tendency would be to revert to the old format. Unless you have any use for chapter metadata, in which case I would add some documentation.
